# Each IceGrid node is an Ansible host. In this example all of them run on
# the local computer. In a real deployment, replace "ansible_connection=local"
# with "ansible_host=<IP address>" for each one.

[nodes]
node1
node2

[all:vars]
ansible_connection=local
ansible_python_interpreter=/usr/bin/python3
lang=py
