services:
  registry:
    image: zeroc/icegridregistry:3.7
    container_name: registry
    hostname: registry
    networks:
      icegrid:
        ipv4_address: 172.28.0.10
    volumes:
      - "./registry.config:/etc/icegridregistry.conf:ro"
    healthcheck:
      test: "bash -c ':> /dev/tcp/127.0.0.1/4061'"
      interval: 1s

  node1:
    build: docker/ignode
    image: ignode
    container_name: node1
    hostname: node1
    depends_on:
      registry:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    networks:
      - icegrid
    volumes:
      - "./node1.config:/etc/icegridnode.conf:ro"
      - "../py:/app"

  deployer:
    image: ignode
    container_name: deployer
    hostname: deployer
    networks:
      - icegrid
    volumes:
      - "./app.xml:/app.xml:ro"
      - "./locator.config:/locator.config:ro"
    command:
      - "/bin/bash"
      - "-c"
      - |
        icegridadmin --Ice.Config=/locator.config -u_ -p_ -e "application add /app.xml" || \
        icegridadmin --Ice.Config=/locator.config -u_ -p_ -e "application update /app.xml"
    depends_on:
      registry:
        condition: service_healthy
      node1:
        condition: service_started
    develop:
      watch:
        - action: restart
          path: ./app.xml

networks:
  icegrid:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
