port 26379

sentinel resolve-hostnames no
sentinel announce-hostnames no
sentinel monitor mymaster 172.28.0.20 6379 2
sentinel auth-pass mymaster ""
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 30000
sentinel parallel-syncs mymaster 1
