// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var Example = __M.module("Example");

    Example.Printer = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 0,
        [
            "::Example::Printer",
            "::Ice::Object"
        ],
        -1, undefined, undefined, false);

    Example.PrinterPrx = Slice.defineProxy(Ice.ObjectPrx, Example.Printer.ice_staticId, undefined);

    Slice.defineOperations(Example.Printer, Example.PrinterPrx,
    {
        "write": [, , , , , , [[7]], , , , ]
    });
    exports.Example = Example;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
